In [1]:
from threeDprediction import *
from threeDprediction_multi import *
from pore_analysis import *
from visualization import *
import os
import numpy as np
from skimage import io
import tensorflow

print("Num GPUs Available: ", len(tensorflow.config.list_physical_devices('GPU')))

Num GPUs Available:  1


# Welcome to the Jupyter Notebook for the utilization of UTILE-Pore

With this notebook, you will be guided through the code and make it possible for you to analyze your porous materials tomographies automatically.

This notebook should help you to run the automated segmentation of the volumes in your images and afterward to apply the diverse functions to extract the information of interest from your data and visualize the results.

Already integrated functions are:

- GDL/porous material
- Pore size distribution analysis of the pores with PoreSpy
- Surface roughness calculation
- Tortuosity simulation with PoreSpy
- Permeability estimation using Kozeny-Carman equation
- Calculation of the solid surface ratio


For MPL
- Layer thickness calculation
- MPL crack analsis (ratio, size distribution, etc.)
- MPL heatmap for thickness variation
- MPL intrusion measurement
- MPL and GDL contact surface calculation

In [2]:
#Give a name to your project

case_name = "Practice"

#First, we need to specify the folder where the tomograph slices (or tif stack) are stored

image_path= "C:/Users/TEAM-CT/Desktop/UTILE-Pore/examples/GDL_Toray602.tif"

#MPL?
mpl = False
#Secondly, we need to specify where is your model stored
if mpl == True:
    model_path = "C:/Users/TEAM-CT/Desktop/UTILE-Pore/models/HRNET_HRNET_multi_fusev2_dataset_noaug_-0.6808-23.keras"
    #is the mpl in the top or the bottom of your stack?
    mpl_place = 'top'
    
else:
    model_path = "C:/Users/TEAM-CT/Desktop/UTILE-Pore/models/HRNET_HRNET_fusev2_utile_noaug_-0.5653-12.keras"

#It is also required to create a folder to store the predicted masks
os.makedirs(f"./{case_name}/", exist_ok=True)

# We set the path to the csv file to store all the extracted data
csv_file = f'./{case_name}/csv_{case_name}.csv'

In [3]:
# Now we start with the segmentation of the volume
# If you just have a porous materials and need a binary segmentation, run the following lines

# input_volume = io.imread('/p/project1/claimd/Andre/Aimy/Dataset/cal_fusev2/test/Toray1202.tif')
# predicted_volume = process_and_predict(image_path, model_path)
# io.imsave(f'./predicted_{case_name}.tif', predicted_volume.astype(np.uint8))

#If you are analyzing a GDL with MPL, then you can run a multiclass semantic segmentation with the following lines:
input_volume = io.imread(image_path)
if mpl:
    if mpl_place != 'top':
         input_volume = np.flip(input_volume, axis=0)
    predicted_volume = process_and_predict_multi(input_volume, model_path)
else:
    predicted_volume = process_and_predict(input_volume, model_path)
io.imsave(f'./{case_name}/predicted_{case_name}.tif', predicted_volume.astype(np.uint8))

INFO:tensorflow:Mixed precision compatibility check (mixed_float16): OK
Your GPU will likely run quickly with dtype policy mixed_float16 as it has compute capability of at least 7.0. Your GPU: NVIDIA GeForce RTX 4080, compute capability 8.9


[16:23:47] INFO     Mixed precision compatibility check (mixed_float16): OK       ]8;id=384417;file://C:\Users\TEAM-CT\miniconda3\envs\pore\lib\site-packages\keras\mixed_precision\device_compatibility_check.py\device_compatibility_check.py]8;;\:]8;id=982405;file://C:\Users\TEAM-CT\miniconda3\envs\pore\lib\site-packages\keras\mixed_precision\device_compatibility_check.py#117\117]8;;\
                    Your GPU will likely run quickly with dtype policy                                             
                    mixed_float16 as it has compute capability of at least 7.0.                                    
                    Your GPU: NVIDIA GeForce RTX 4080, compute capability 8.9                                      

Patch processed: 1 of 647
Patch processed: 2 of 647
Patch processed: 3 of 647
Patch processed: 4 of 647
Patch processed: 5 of 647
Patch processed: 6 of 647
Patch processed: 7 of 647
Patch processed: 8 of 647
Patch processed: 9 of 647
Patch processed: 10 of 647
Patch processed: 11 of 647
Patch processed: 12 of 647
Patch processed: 13 of 647
Patch processed: 14 of 647
Patch processed: 15 of 647
Patch processed: 16 of 647
Patch processed: 17 of 647
Patch processed: 18 of 647
Patch processed: 19 of 647
Patch processed: 20 of 647
Patch processed: 21 of 647
Patch processed: 22 of 647
Patch processed: 23 of 647
Patch processed: 24 of 647
Patch processed: 25 of 647
Patch processed: 26 of 647
Patch processed: 27 of 647
Patch processed: 28 of 647
Patch processed: 29 of 647
Patch processed: 30 of 647
Patch processed: 31 of 647
Patch processed: 32 of 647
Patch processed: 33 of 647
Patch processed: 34 of 647
Patch processed: 35 of 647
Patch processed: 36 of 647
Patch processed: 37 of 647
Patch proc

C:\Users\TEAM-CT\AppData\Local\Temp\ipykernel_28104\1867088724.py:14: UserWarning: ./Practice/predicted_Practice.tif is a low contrast image
  io.imsave(f'./{case_name}/predicted_{case_name}.tif', predicted_volume.astype(np.uint8))


In [5]:
# Now, lets visualize the segmented volume
predicted_volume = io.imread(f'./{case_name}/predicted_{case_name}.tif')
visualize_volume(predicted_volume, case_name, False)

In [6]:
# We can directly start wiht the property extraction of the porous material or GDL
porosity, results, avg_pore, sd = calculate_psd(predicted_volume, csv_file, case_name, voxel_size=5)

Porosity: 0.8173695886875261


  0%|          | 0/25 [00:00<?, ?it/s]

Sizes shape: (29, 2289, 1125)
Results: ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Results of pore_size_distribution generated at Wed Sep 25 16:30:00 2024
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
LogR                      Array of size (10,)
pdf                       Array of size (10,)
cdf                       Array of size (10,)
satn                      Array of size (10,)
bin_centers               Array of size (10,)
bin_edges                 Array of size (11,)
bin_widths                Array of size (10,)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Average Pore Size (microns): 4.695925698026362
Standard Deviation (microns): 2.7128125048061142


In [7]:
#Tortuosity simulation (for non-optimized devices can take several hours)
tortuosity = 1.85
#tortuosity = tortuosity_simulation(predicted_volume, csv_file)

In [8]:
# Having the above mentioned properties, we can estimate the permeability
# Estimate permeability
ssa = calculate_ssa(predicted_volume)
permeability = estimate_permeability(porosity, csv_file, ssa, tortuosity)
print(f'Permeability: {permeability}')

Permeability: 71.85213454431745


In [9]:
# Then surface roughness calculation of the material
#Calculate surface roughness
Ra, Rq = calculate_surface_roughness_from_surface(predicted_volume)
with open(csv_file, 'a', newline='') as csvfile:
        writer = csv.writer(csvfile)
        # Write data
        writer.writerow(['##### Surface roughness #####'])
        writer.writerow(['Arithmetic_Mean_Roughness_(Ra)', Ra])
        writer.writerow(['Root_Mean_Square_Roughness_(Rq)', Rq])
print(f"Arithmetic Mean Roughness (Ra): {Ra}")
print(f"Root Mean Square Roughness (Rq): {Rq}")


[2.220446e-16 1.000000e+00 2.220446e-16 ... 9.000000e+00 9.000000e+00
 9.000000e+00]
Arithmetic Mean Roughness (Ra): 11.764146089553833
Root Mean Square Roughness (Rq): 13.628153800964355


In [10]:
#Calculacte solid surface ratio
calculate_solid_surface_ratio(predicted_volume, csv_file, gdl=1, side='bottom')

(2289, 1125)
Solid surface ratio: 0.22939507790883937


0.22939507790883937

In [11]:
# Now we can move to the functions specialized for MPL containing GDLs
# We can caluclate the MPL and GDL thickness
MPL_GDL_thickness(predicted_volume, csv_file, axis=0, mpl=2, gdl=1)


GDL thickness:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [8]:
#Calculate MPL crack analysis
crack_ratio, crack_count, crack_labels, crack_sizes, slice_image = MPL_crack_analysis(predicted_volume,case_name, csv_file, from_top=True)
print(f"Crack Ratio: {crack_ratio}")
print(f"Crack Count: {crack_count}")
#print(f"Crack Sizes: {crack_sizes}")
plot_crack_labels(slice_image, case_name, crack_labels)


Crack Ratio: 0.14224191750278703
Crack Count: 236


In [12]:
# Example usage:
Ra, Rq, Ra_std_dev, Ra_CoV, avg_thickness = MPL_intrusion_roughness(predicted_volume, csv_file, mpl=2, voxel_size=5, from_top=True)
print(f"Global Roughness Ra: {Ra}, Rq: {Rq}")
print(f"Standard Deviation of Local Ra: {Ra_std_dev}")
print(f"Coefficient of Variation of Local Ra: {Ra_CoV}")
print(f"Average Thickness: {avg_thickness}")

mpl Thickness 0


ValueError: zero-size array to reduction operation maximum which has no identity

In [13]:
# MPL heatmap creation
MPL_heatmap(predicted_volume,case_name, 2)

In [7]:
# Calculate fiber touching MPL voxels
MPL_count_touching_voxels(predicted_volume, csv_file, mpl_class=2, fiber_class=1)

MPL voxels touching GDL:  120039


120039

In [ ]:
# Calculate the pores and throats of the pore structure with the Snow algorithm and save them as a pickle file
if mpl == True:
    predicted_volume = np.where(predicted_volume==1, 1,0) #Do this to remove the mpl and do the analysis only on the GDL
snow_network_from_image(predicted_volume, case_name)